from fastapi import FastAPI
from pydantic import BaseModel
import httpx
import os
from dotenv import load_dotenv

load_dotenv()

app = FastAPI()

TELEGRAM_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

route_prices = {
("Antalya Havaliman", "Kemer(Beldibi)"): 50,
("Antalya Havaliman", "Kemer(Göynük)"): 50,
("Antalya Havaliman", "Kemer"): 50,
("Antalya Havaliman", "Kemer(Kiriş)"): 60,
("Antalya Havaliman", "Kemer(Çamyuva)"): 60,
("Antalya Havaliman", "Kemer(Tekirova)"): 60,
("Antalya Havaliman", "Antalya(Kundu)"): 30,
("Antalya Havaliman", "Antalya(Lara)"): 30,
("Antalya Havaliman", "Antalya(Konyaaltı)"): 40,
("Antalya Havaliman", "Belek(Kadriye)"): 50,
("Antalya Havaliman", "Belek"): 50,
("Antalya Havaliman", "Belek(Bogazkent)"): 50,
("Antalya Havaliman", "Side(Gundoğdu)"): 60,
("Antalya Havaliman", "Side(Çolaklı)"): 60,
("Antalya Havaliman", "Side"): 60,
("Antalya Havaliman", "Side(Sorgun)"): 60,
("Antalya Havaliman", "Side(Kızılağaç)"): 60,
("Antalya Havaliman", "Side(Kızılot)"): 60,
("Antalya Havaliman", "Side(Çenger)"): 65,
("Antalya Havaliman", "Alanya(Okurcalar)"): 65,
("Antalya Havaliman", "Alanya(Avsallar)"): 70,
("Antalya Havaliman", "Alanya(Konaklı)"): 80,
("Antalya Havaliman", "Alanya"): 95,
("Antalya Havaliman", "Alanya(Mahmutlar)"): 100,
("Antalya Havaliman", "Antalya(AVM)"): 50,
("Antalya Havaliman", "Diğer"): 0,
("Kemer(Beldibi)", "Antalya Havaliman"): 50,
("Kemer(Beldibi)", "Kemer(Göynük)"): 30,
("Kemer(Beldibi)", "Kemer"): 30,
("Kemer(Beldibi)", "Kemer(Kiriş)"): 30,
("Kemer(Beldibi)", "Kemer(Çamyuva)"): 40,
("Kemer(Beldibi)", "Kemer(Tekirova)"): 40,
("Kemer(Beldibi)", "Antalya(Kundu)"): 70,
("Kemer(Beldibi)", "Antalya(Lara)"): 50,
("Kemer(Beldibi)", "Antalya(Konyaaltı)"): 50,
("Kemer(Beldibi)", "Belek(Kadriye)"): 90,
("Kemer(Beldibi)", "Belek"): 90,
("Kemer(Beldibi)", "Belek(Bogazkent)"): 90,
("Kemer(Beldibi)", "Side(Gundoğdu)"): 100,
("Kemer(Beldibi)", "Side(Çolaklı)"): 100,
("Kemer(Beldibi)", "Side"): 100,
("Kemer(Beldibi)", "Side(Sorgun)"): 100,
("Kemer(Beldibi)", "Side(Kızılağaç)"): 100,
("Kemer(Beldibi)", "Side(Kızılot)"): 100,
("Kemer(Beldibi)", "Side(Çenger)"): 105,
("Kemer(Beldibi)", "Alanya(Okurcalar)"): 105,
("Kemer(Beldibi)", "Alanya(Avsallar)"): 110,
("Kemer(Beldibi)", "Alanya(Konaklı)"): 120,
("Kemer(Beldibi)", "Alanya"): 135,
("Kemer(Beldibi)", "Alanya(Mahmutlar)"): 140,
("Kemer(Beldibi)", "Antalya(AVM)"): 100,
("Kemer(Beldibi)", "Diğer"): 0,
("Kemer(Göynük)", "Antalya Havaliman"): 50,
("Kemer(Göynük)", "Kemer(Beldibi)"): 30,
("Kemer(Göynük)", "Kemer"): 30,
("Kemer(Göynük)", "Kemer(Kiriş)"): 30,
("Kemer(Göynük)", "Kemer(Çamyuva)"): 40,
("Kemer(Göynük)", "Kemer(Tekirova)"): 40,
("Kemer(Göynük)", "Antalya(Kundu)"): 70,
("Kemer(Göynük)", "Antalya(Lara)"): 50,
("Kemer(Göynük)", "Antalya(Konyaaltı)"): 50,
("Kemer(Göynük)", "Belek(Kadriye)"): 90,
("Kemer(Göynük)", "Belek"): 90,
("Kemer(Göynük)", "Belek(Bogazkent)"): 90,
("Kemer(Göynük)", "Side(Gundoğdu)"): 100,
("Kemer(Göynük)", "Side(Çolaklı)"): 100,
("Kemer(Göynük)", "Side"): 100,
("Kemer(Göynük)", "Side(Sorgun)"): 100,
("Kemer(Göynük)", "Side(Kızılağaç)"): 100,
("Kemer(Göynük)", "Side(Kızılot)"): 100,
("Kemer(Göynük)", "Side(Çenger)"): 105,
("Kemer(Göynük)", "Alanya(Okurcalar)"): 105,
("Kemer(Göynük)", "Alanya(Avsallar)"): 110,
("Kemer(Göynük)", "Alanya(Konaklı)"): 120,
("Kemer(Göynük)", "Alanya"): 135,
("Kemer(Göynük)", "Alanya(Mahmutlar)"): 140,
("Kemer(Göynük)", "Antalya(AVM)"): 100,
("Kemer(Göynük)", "Diğer"): 0,
("Kemer", "Antalya Havaliman"): 50,
("Kemer", "Kemer(Beldibi)"): 30,
("Kemer", "Kemer(Göynük)"): 30,
("Kemer", "Kemer(Kiriş)"): 30,
("Kemer", "Kemer(Çamyuva)"): 40,
("Kemer", "Kemer(Tekirova)"): 40,
("Kemer", "Antalya(Kundu)"): 70,
("Kemer", "Antalya(Lara)"): 50,
("Kemer", "Antalya(Konyaaltı)"): 50,
("Kemer", "Belek(Kadriye)"): 90,
("Kemer", "Belek"): 90,
("Kemer", "Belek(Bogazkent)"): 90,
("Kemer", "Side(Gundoğdu)"): 100,
("Kemer", "Side(Çolaklı)"): 100,
("Kemer", "Side"): 100,
("Kemer", "Side(Sorgun)"): 100,
("Kemer", "Side(Kızılağaç)"): 100,
("Kemer", "Side(Kızılot)"): 100,
("Kemer", "Side(Çenger)"): 105,
("Kemer", "Alanya(Okurcalar)"): 105,
("Kemer", "Alanya(Avsallar)"): 110,
("Kemer", "Alanya(Konaklı)"): 120,
("Kemer", "Alanya"): 135,
("Kemer", "Alanya(Mahmutlar)"): 140,
("Kemer", "Antalya(AVM)"): 100,
("Kemer", "Diğer"): 0,
("Kemer(Kiriş)", "Antalya Havaliman"): 60,
("Kemer(Kiriş)", "Kemer(Beldibi)"): 40,
("Kemer(Kiriş)", "Kemer(Göynük)"): 40,
("Kemer(Kiriş)", "Kemer"): 40,
("Kemer(Kiriş)", "Kemer(Çamyuva)"): 30,
("Kemer(Kiriş)", "Kemer(Tekirova)"): 30,
("Kemer(Kiriş)", "Antalya(Kundu)"): 80,
("Kemer(Kiriş)", "Antalya(Lara)"): 60,
("Kemer(Kiriş)", "Antalya(Konyaaltı)"): 60,
("Kemer(Kiriş)", "Belek(Kadriye)"): 100,
("Kemer(Kiriş)", "Belek"): 100,
("Kemer(Kiriş)", "Belek(Bogazkent)"): 100,
("Kemer(Kiriş)", "Side(Gundoğdu)"): 110,
("Kemer(Kiriş)", "Side(Çolaklı)"): 110,
("Kemer(Kiriş)", "Side"): 110,
("Kemer(Kiriş)", "Side(Sorgun)"): 110,
("Kemer(Kiriş)", "Side(Kızılağaç)"): 110,
("Kemer(Kiriş)", "Side(Kızılot)"): 110,
("Kemer(Kiriş)", "Side(Çenger)"): 115,
("Kemer(Kiriş)", "Alanya(Okurcalar)"): 115,
("Kemer(Kiriş)", "Alanya(Avsallar)"): 120,
("Kemer(Kiriş)", "Alanya(Konaklı)"): 130,
("Kemer(Kiriş)", "Alanya"): 145,
("Kemer(Kiriş)", "Alanya(Mahmutlar)"): 150,
("Kemer(Kiriş)", "Antalya(AVM)"): 120,
("Kemer(Kiriş)", "Diğer"): 0,
("Kemer(Çamyuva)", "Antalya Havaliman"): 60,
("Kemer(Çamyuva)", "Kemer(Beldibi)"): 40,
("Kemer(Çamyuva)", "Kemer(Göynük)"): 40,
("Kemer(Çamyuva)", "Kemer(Kiriş)"): 30,
("Kemer(Çamyuva)", "Kemer"): 40,
("Kemer(Çamyuva)", "Kemer(Tekirova)"): 30,
("Kemer(Çamyuva)", "Antalya(Kundu)"): 80,
("Kemer(Çamyuva)", "Antalya(Lara)"): 60,
("Kemer(Çamyuva)", "Antalya(Konyaaltı)"): 60,
("Kemer(Çamyuva)", "Belek(Kadriye)"): 100,
("Kemer(Çamyuva)", "Belek"): 100,
("Kemer(Çamyuva)", "Belek(Bogazkent)"): 100,
("Kemer(Çamyuva)", "Side(Gundoğdu)"): 110,
("Kemer(Çamyuva)", "Side(Çolaklı)"): 110,
("Kemer(Çamyuva)", "Side"): 110,
("Kemer(Çamyuva)", "Side(Sorgun)"): 110,
("Kemer(Çamyuva)", "Side(Kızılağaç)"): 110,
("Kemer(Çamyuva)", "Side(Kızılot)"): 110,
("Kemer(Çamyuva)", "Side(Çenger)"): 115,
("Kemer(Çamyuva)", "Alanya(Okurcalar)"): 115,
("Kemer(Çamyuva)", "Alanya(Avsallar)"): 120,
("Kemer(Çamyuva)", "Alanya(Konaklı)"): 130,
("Kemer(Çamyuva)", "Alanya"): 145,
("Kemer(Çamyuva)", "Alanya(Mahmutlar)"): 150,
("Kemer(Çamyuva)", "Antalya(AVM)"): 120,
("Kemer(Çamyuva)", "Diğer"): 0,
("Kemer(Tekirova)", "Antalya Havaliman"): 60,
("Kemer(Tekirova)", "Kemer(Beldibi)"): 40,
("Kemer(Tekirova)", "Kemer(Göynük)"): 40,
("Kemer(Tekirova)", "Kemer(Kiriş)"): 30,
("Kemer(Tekirova)", "Kemer"): 40,
("Kemer(Tekirova)", "Kemer(Çamyuva)"): 30,
("Kemer(Tekirova)", "Antalya(Kundu)"): 80,
("Kemer(Tekirova)", "Antalya(Lara)"): 60,
("Kemer(Tekirova)", "Antalya(Konyaaltı)"): 60,
("Kemer(Tekirova)", "Belek(Kadriye)"): 100,
("Kemer(Tekirova)", "Belek"): 100,
("Kemer(Tekirova)", "Belek(Bogazkent)"): 100,
("Kemer(Tekirova)", "Side(Gundoğdu)"): 110,
("Kemer(Tekirova)", "Side(Çolaklı)"): 110,
("Kemer(Tekirova)", "Side"): 110,
("Kemer(Tekirova)", "Side(Sorgun)"): 110,
("Kemer(Tekirova)", "Side(Kızılağaç)"): 110,
("Kemer(Tekirova)", "Side(Kızılot)"): 110,
("Kemer(Tekirova)", "Side(Çenger)"): 115,
("Kemer(Tekirova)", "Alanya(Okurcalar)"): 115,
("Kemer(Tekirova)", "Alanya(Avsallar)"): 120,
("Kemer(Tekirova)", "Alanya(Konaklı)"): 130,
("Kemer(Tekirova)", "Alanya"): 145,
("Kemer(Tekirova)", "Alanya(Mahmutlar)"): 150,
("Kemer(Tekirova)", "Antalya(AVM)"): 120,
("Kemer(Tekirova)", "Diğer"): 0,
("Antalya(Kundu)", "Antalya Havaliman"): 30,
("Antalya(Kundu)", "Kemer(Beldibi)"): 60,
("Antalya(Kundu)", "Kemer(Göynük)"): 60,
("Antalya(Kundu)", "Kemer(Kiriş)"): 70,
("Antalya(Kundu)", "Kemer"): 60,
("Antalya(Kundu)", "Kemer(Çamyuva)"): 70,
("Antalya(Kundu)", "Kemer(Tekirova)"): 70,
("Antalya(Kundu)", "Antalya(Lara)"): 30,
("Antalya(Kundu)", "Antalya(Konyaaltı)"): 40,
("Antalya(Kundu)", "Belek(Kadriye)"): 50,
("Antalya(Kundu)", "Belek"): 50,
("Antalya(Kundu)", "Belek(Bogazkent)"): 50,
("Antalya(Kundu)", "Side(Gundoğdu)"): 60,
("Antalya(Kundu)", "Side(Çolaklı)"): 60,
("Antalya(Kundu)", "Side"): 60,
("Antalya(Kundu)", "Side(Sorgun)"): 60,
("Antalya(Kundu)", "Side(Kızılağaç)"): 60,
("Antalya(Kundu)", "Side(Kızılot)"): 60,
("Antalya(Kundu)", "Side(Çenger)"): 65,
("Antalya(Kundu)", "Alanya(Okurcalar)"): 65,
("Antalya(Kundu)", "Alanya(Avsallar)"): 70,
("Antalya(Kundu)", "Alanya(Konaklı)"): 80,
("Antalya(Kundu)", "Alanya"): 95,
("Antalya(Kundu)", "Alanya(Mahmutlar)"): 100,
("Antalya(Kundu)", "Antalya(AVM)"): 60,
("Antalya(Kundu)", "Diğer"): 0,
("Antalya(Lara)", "Antalya Havaliman"): 30,
("Antalya(Lara)", "Kemer(Beldibi)"): 60,
("Antalya(Lara)", "Kemer(Göynük)"): 60,
("Antalya(Lara)", "Kemer(Kiriş)"): 70,
("Antalya(Lara)", "Kemer"): 60,
("Antalya(Lara)", "Kemer(Çamyuva)"): 70,
("Antalya(Lara)", "Kemer(Tekirova)"): 70,
("Antalya(Lara)", "Antalya(Kundu)"): 30,
("Antalya(Lara)", "Antalya(Konyaaltı)"): 30,
("Antalya(Lara)", "Belek(Kadriye)"): 50,
("Antalya(Lara)", "Belek"): 50,
("Antalya(Lara)", "Belek(Boğazkent)"): 60,
("Antalya(Lara)", "Side(Gundoğdu)"): 60,
("Antalya(Lara)", "Side(Çolaklı)"): 60,
("Antalya(Lara)", "Side"): 60,
("Antalya(Lara)", "Side(Sorgun)"): 60,
("Antalya(Lara)", "Side(Kızılağaç)"): 60,
("Antalya(Lara)", "Side(Kızılot)"): 60,
("Antalya(Lara)", "Side(Çenger)"): 65,
("Antalya(Lara)", "Alanya(Okurcalar)"): 65,
("Antalya(Lara)", "Alanya(Avsallar)"): 70,
("Antalya(Lara)", "Alanya(Konaklı)"): 80,
("Antalya(Lara)", "Alanya"): 95,
("Antalya(Lara)", "Alanya(Mahmutlar)"): 100,
("Antalya(Lara)", "Antalya(AVM)"): 60,
("Antalya(Lara)", "Diğer"): 0,
("Antalya(Konyaaltı)", "Antalya Havaliman"): 40,
("Antalya(Konyaaltı)", "Kemer(Beldibi)"): 50,
("Antalya(Konyaaltı)", "Kemer(Göynük)"): 50,
("Antalya(Konyaaltı)", "Kemer(Kiriş)"): 60,
("Antalya(Konyaaltı)", "Kemer"): 50,
("Antalya(Konyaaltı)", "Kemer(Çamyuva)"): 60,
("Antalya(Konyaaltı)", "Kemer(Tekirova)"): 60,
("Antalya(Konyaaltı)", "Antalya(Kundu)"): 40,
("Antalya(Konyaaltı)", "Antalya(Lara)"): 40,
("Antalya(Konyaaltı)", "Belek(Kadriye)"): 70,
("Antalya(Konyaaltı)", "Belek"): 70,
("Antalya(Konyaaltı)", "Belek(Boğazkent)"): 80,
("Antalya(Konyaaltı)", "Side(Gundoğdu)"): 80,
("Antalya(Konyaaltı)", "Side(Çolaklı)"): 80,
("Antalya(Konyaaltı)", "Side"): 80,
("Antalya(Konyaaltı)", "Side(Sorgun)"): 80,
("Antalya(Konyaaltı)", "Side(Kızılağaç)"): 80,
("Antalya(Konyaaltı)", "Side(Kızılot)"): 80,
("Antalya(Konyaaltı)", "Side(Çenger)"): 85,
("Antalya(Konyaaltı)", "Alanya(Okurcalar)"): 85,
("Antalya(Konyaaltı)", "Alanya(Avsallar)"): 90,
("Antalya(Konyaaltı)", "Alanya(Konaklı)"): 100,
("Antalya(Konyaaltı)", "Alanya"): 115,
("Antalya(Konyaaltı)", "Alanya(Mahmutlar)"): 120,
("Antalya(Konyaaltı)", "Antalya(AVM)"): 60,
("Antalya(Konyaaltı)", "Diğer"): 0,
("Belek(Kadriye)", "Antalya Havaliman"): 50,
("Belek(Kadriye)", "Kemer(Beldibi)"): 90,
("Belek(Kadriye)", "Kemer(Göynük)"): 90,
("Belek(Kadriye)", "Kemer(Kiriş)"): 100,
("Belek(Kadriye)", "Kemer"): 90,
("Belek(Kadriye)", "Kemer(Çamyuva)"): 100,
("Belek(Kadriye)", "Kemer(Tekirova)"): 100,
("Belek(Kadriye)", "Antalya(Kundu)"): 40,
("Belek(Kadriye)", "Antalya(Lara)"): 50,
("Belek(Kadriye)", "Antalya(Konyaaltı)"): 70,
("Belek(Kadriye)", "Belek"): 30,
("Belek(Kadriye)", "Belek(Boğazkent)"): 30,
("Belek(Kadriye)", "Side(Gundoğdu)"): 50,
("Belek(Kadriye)", "Side(Çolaklı)"): 50,
("Belek(Kadriye)", "Side"): 50,
("Belek(Kadriye)", "Side(Sorgun)"): 50,
("Belek(Kadriye)", "Side(Kızılağaç)"): 50,
("Belek(Kadriye)", "Side(Kızılot)"): 50,
("Belek(Kadriye)", "Side(Çenger)"): 55,
("Belek(Kadriye)", "Alanya(Okurcalar)"): 55,
("Belek(Kadriye)", "Alanya(Avsallar)"): 60,
("Belek(Kadriye)", "Alanya(Konaklı)"): 70,
("Belek(Kadriye)", "Alanya"): 85,
("Belek(Kadriye)", "Alanya(Mahmutlar)"): 90,
("Belek(Kadriye)", "Antalya(AVM)"): 100,
("Belek(Kadriye)", "Diğer"): 0,
("Belek", "Antalya Havaliman"): 50,
("Belek", "Kemer(Beldibi)"): 90,
("Belek", "Kemer(Göynük)"): 90,
("Belek", "Kemer(Kiriş)"): 100,
("Belek", "Kemer"): 90,
("Belek", "Kemer(Çamyuva)"): 100,
("Belek", "Kemer(Tekirova)"): 100,
("Belek", "Antalya(Kundu)"): 40,
("Belek", "Antalya(Lara)"): 50,
("Belek", "Antalya(Konyaaltı)"): 70,
("Belek", "Belek(Kadriye)"): 30,
("Belek", "Belek(Boğazkent)"): 30,
("Belek", "Side(Gundoğdu)"): 50,
("Belek", "Side(Çolaklı)"): 50,
("Belek", "Side"): 50,
("Belek", "Side(Sorgun)"): 50,
("Belek", "Side(Kızılağaç)"): 50,
("Belek", "Side(Kızılot)"): 50,
("Belek", "Side(Çenger)"): 55,
("Belek", "Alanya(Okurcalar)"): 55,
("Belek", "Alanya(Avsallar)"): 60,
("Belek", "Alanya(Konaklı)"): 70,
("Belek", "Alanya"): 85,
("Belek", "Alanya(Mahmutlar)"): 90,
("Belek", "Antalya(AVM)"): 100,
("Belek", "Diğer"): 0,
("Belek(Boğazkent)", "Antalya Havaliman"): 50,
("Belek(Boğazkent)", "Kemer(Beldibi)"): 90,
("Belek(Boğazkent)", "Kemer(Göynük)"): 90,
("Belek(Boğazkent)", "Kemer(Kiriş)"): 100,
("Belek(Boğazkent)", "Kemer"): 90,
("Belek(Boğazkent)", "Kemer(Çamyuva)"): 100,
("Belek(Boğazkent)", "Kemer(Tekirova)"): 100,
("Belek(Boğazkent)", "Antalya(Kundu)"): 40,
("Belek(Boğazkent)", "Antalya(Lara)"): 50,
("Belek(Boğazkent)", "Antalya(Konyaaltı)"): 70,
("Belek(Boğazkent)", "Belek(Kadriye)"): 30,
("Belek(Boğazkent)", "Belek"): 30,
("Belek(Boğazkent)", "Side(Gundoğdu)"): 50,
("Belek(Boğazkent)", "Side(Çolaklı)"): 50,
("Belek(Boğazkent)", "Side"): 50,
("Belek(Boğazkent)", "Side(Sorgun)"): 50,
("Belek(Boğazkent)", "Side(Kızılağaç)"): 50,
("Belek(Boğazkent)", "Side(Kızılot)"): 50,
("Belek(Boğazkent)", "Side(Çenger)"): 55,
("Belek(Boğazkent)", "Alanya(Okurcalar)"): 55,
("Belek(Boğazkent)", "Alanya(Avsallar)"): 60,
("Belek(Boğazkent)", "Alanya(Konaklı)"): 70,
("Belek(Boğazkent)", "Alanya"): 85,
("Belek(Boğazkent)", "Alanya(Mahmutlar)"): 90,
("Belek(Boğazkent)", "Antalya(AVM)"): 100,
("Belek(Boğazkent)", "Diğer"): 0,
("Side(Gundoğdu)", "Antalya Havaliman"): 60,
("Side(Gundoğdu)", "Kemer(Beldibi)"): 100,
("Side(Gundoğdu)", "Kemer(Göynük)"): 100,
("Side(Gundoğdu)", "Kemer(Kiriş)"): 110,
("Side(Gundoğdu)", "Kemer"): 100,
("Side(Gundoğdu)", "Kemer(Çamyuva)"): 110,
("Side(Gundoğdu)", "Kemer(Tekirova)"): 110,
("Side(Gundoğdu)", "Antalya(Kundu)"): 60,
("Side(Gundoğdu)", "Antalya(Lara)"): 60,
("Side(Gundoğdu)", "Antalya(Konyaaltı)"): 80,
("Side(Gundoğdu)", "Belek(Kadriye)"): 50,
("Side(Gundoğdu)", "Belek"): 50,
("Side(Gundoğdu)", "Belek(Boğazkent)"): 50,
("Side(Gundoğdu)", "Side(Çolaklı)"): 30,
("Side(Gundoğdu)", "Side"): 30,
("Side(Gundoğdu)", "Side(Sorgun)"): 30,
("Side(Gundoğdu)", "Side(Kızılağaç)"): 30,
("Side(Gundoğdu)", "Side(Kızılot)"): 30,
("Side(Gundoğdu)", "Side(Çenger)"): 35,
("Side(Gundoğdu)", "Alanya(Okurcalar)"): 45,
("Side(Gundoğdu)", "Alanya(Avsallar)"): 50,
("Side(Gundoğdu)", "Alanya(Konaklı)"): 60,
("Side(Gundoğdu)", "Alanya"): 75,
("Side(Gundoğdu)", "Alanya(Mahmutlar)"): 80,
("Side(Gundoğdu)", "Antalya(AVM)"): 120,
("Side(Gundoğdu)", "Diğer"): 0,
("Side(Çolaklı)", "Antalya Havaliman"): 60,
("Side(Çolaklı)", "Kemer(Beldibi)"): 100,
("Side(Çolaklı)", "Kemer(Göynük)"): 100,
("Side(Çolaklı)", "Kemer(Kiriş)"): 110,
("Side(Çolaklı)", "Kemer"): 100,
("Side(Çolaklı)", "Kemer(Çamyuva)"): 110,
("Side(Çolaklı)", "Kemer(Tekirova)"): 110,
("Side(Çolaklı)", "Antalya(Kundu)"): 60,
("Side(Çolaklı)", "Antalya(Lara)"): 60,
("Side(Çolaklı)", "Antalya(Konyaaltı)"): 80,
("Side(Çolaklı)", "Belek(Kadriye)"): 50,
("Side(Çolaklı)", "Belek"): 50,
("Side(Çolaklı)", "Belek(Boğazkent)"): 50,
("Side(Çolaklı)", "Side(Gundoğdu)"): 30,
("Side(Çolaklı)", "Side"): 30,
("Side(Çolaklı)", "Side(Sorgun)"): 30,
("Side(Çolaklı)", "Side(Kızılağaç)"): 30,
("Side(Çolaklı)", "Side(Kızılot)"): 30,
("Side(Çolaklı)", "Side(Çenger)"): 35,
("Side(Çolaklı)", "Alanya(Okurcalar)"): 45,
("Side(Çolaklı)", "Alanya(Avsallar)"): 50,
("Side(Çolaklı)", "Alanya(Konaklı)"): 60,
("Side(Çolaklı)", "Alanya"): 75,
("Side(Çolaklı)", "Alanya(Mahmutlar)"): 80,
("Side(Çolaklı)", "Antalya(AVM)"): 120,
("Side(Çolaklı)", "Diğer"): 0,
("Side", "Antalya Havaliman"): 60,
("Side", "Kemer(Beldibi)"): 100,
("Side", "Kemer(Göynük)"): 100,
("Side", "Kemer(Kiriş)"): 110,
("Side", "Kemer"): 100,
("Side", "Kemer(Çamyuva)"): 110,
("Side", "Kemer(Tekirova)"): 110,
("Side", "Antalya(Kundu)"): 60,
("Side", "Antalya(Lara)"): 60,
("Side", "Antalya(Konyaaltı)"): 80,
("Side", "Belek(Kadriye)"): 50,
("Side", "Belek"): 50,
("Side", "Belek(Boğazkent)"): 50,
("Side", "Side(Gundoğdu)"): 30,
("Side", "Side(Çolaklı)"): 30,
("Side", "Side(Sorgun)"): 30,
("Side", "Side(Kızılağaç)"): 30,
("Side", "Side(Kızılot)"): 30,
("Side", "Side(Çenger)"): 35,
("Side", "Alanya(Okurcalar)"): 45,
("Side", "Alanya(Avsallar)"): 50,
("Side", "Alanya(Konaklı)"): 60,
("Side", "Alanya"): 75,
("Side", "Alanya(Mahmutlar)"): 80,
("Side", "Antalya(AVM)"): 120,
("Side", "Diğer"): 0,
("Side(Sorgun)", "Antalya Havaliman"): 60,
("Side(Sorgun)", "Kemer(Beldibi)"): 100,
("Side(Sorgun)", "Kemer(Göynük)"): 100,
("Side(Sorgun)", "Kemer(Kiriş)"): 110,
("Side(Sorgun)", "Kemer"): 100,
("Side(Sorgun)", "Kemer(Çamyuva)"): 110,
("Side(Sorgun)", "Kemer(Tekirova)"): 110,
("Side(Sorgun)", "Antalya(Kundu)"): 60,
("Side(Sorgun)", "Antalya(Lara)"): 60,
("Side(Sorgun)", "Antalya(Konyaaltı)"): 80,
("Side(Sorgun)", "Belek(Kadriye)"): 50,
("Side(Sorgun)", "Belek"): 50,
("Side(Sorgun)", "Belek(Boğazkent)"): 50,
("Side(Sorgun)", "Side(Gundoğdu)"): 30,
("Side(Sorgun)", "Side(Çolaklı)"): 30,
("Side(Sorgun)", "Side"): 30,
("Side(Sorgun)", "Side(Kızılağaç)"): 30,
("Side(Sorgun)", "Side(Kızılot)"): 30,
("Side(Sorgun)", "Side(Çenger)"): 35,
("Side(Sorgun)", "Alanya(Okurcalar)"): 45,
("Side(Sorgun)", "Alanya(Avsallar)"): 50,
("Side(Sorgun)", "Alanya(Konaklı)"): 60,
("Side(Sorgun)", "Alanya"): 75,
("Side(Sorgun)", "Alanya(Mahmutlar)"): 80,
("Side(Sorgun)", "Antalya(AVM)"): 120,
("Side(Sorgun)", "Diğer"): 0,
("Side(Kızılağaç)", "Antalya Havaliman"): 60,
("Side(Kızılağaç)", "Kemer(Beldibi)"): 100,
("Side(Kızılağaç)", "Kemer(Göynük)"): 100,
("Side(Kızılağaç)", "Kemer(Kiriş)"): 110,
("Side(Kızılağaç)", "Kemer"): 100,
("Side(Kızılağaç)", "Kemer(Çamyuva)"): 110,
("Side(Kızılağaç)", "Kemer(Tekirova)"): 110,
("Side(Kızılağaç)", "Antalya(Kundu)"): 60,
("Side(Kızılağaç)", "Antalya(Lara)"): 60,
("Side(Kızılağaç)", "Antalya(Konyaaltı)"): 80,
("Side(Kızılağaç)", "Belek(Kadriye)"): 50,
("Side(Kızılağaç)", "Belek"): 50,
("Side(Kızılağaç)", "Belek(Boğazkent)"): 50,
("Side(Kızılağaç)", "Side(Gundoğdu)"): 30,
("Side(Kızılağaç)", "Side(Çolaklı)"): 30,
("Side(Kızılağaç)", "Side"): 30,
("Side(Kızılağaç)", "Side(Sorgun)"): 30,
("Side(Kızılağaç)", "Side(Kızılot)"): 30,
("Side(Kızılağaç)", "Side(Çenger)"): 35,
("Side(Kızılağaç)", "Alanya(Okurcalar)"): 45,
("Side(Kızılağaç)", "Alanya(Avsallar)"): 50,
("Side(Kızılağaç)", "Alanya(Konaklı)"): 60,
("Side(Kızılağaç)", "Alanya"): 75,
("Side(Kızılağaç)", "Alanya(Mahmutlar)"): 80,
("Side(Kızılağaç)", "Antalya(AVM)"): 120,
("Side(Kızılağaç)", "Diğer"): 0,
("Side(Kızılot)", "Antalya Havaliman"): 60,
("Side(Kızılot)", "Kemer(Beldibi)"): 100,
("Side(Kızılot)", "Kemer(Göynük)"): 100,
("Side(Kızılot)", "Kemer(Kiriş)"): 110,
("Side(Kızılot)", "Kemer"): 100,
("Side(Kızılot)", "Kemer(Çamyuva)"): 110,
("Side(Kızılot)", "Kemer(Tekirova)"): 110,
("Side(Kızılot)", "Antalya(Kundu)"): 60,
("Side(Kızılot)", "Antalya(Lara)"): 60,
("Side(Kızılot)", "Antalya(Konyaaltı)"): 80,
("Side(Kızılot)", "Belek(Kadriye)"): 50,
("Side(Kızılot)", "Belek"): 50,
("Side(Kızılot)", "Belek(Boğazkent)"): 50,
("Side(Kızılot)", "Side(Gundoğdu)"): 30,
("Side(Kızılot)", "Side(Çolaklı)"): 30,
("Side(Kızılot)", "Side"): 30,
("Side(Kızılot)", "Side(Sorgun)"): 30,
("Side(Kızılot)", "Side(Kızılağaç)"): 30,
("Side(Kızılot)", "Side(Çenger)"): 30,
("Side(Kızılot)", "Alanya(Okurcalar)"): 45,
("Side(Kızılot)", "Alanya(Avsallar)"): 50,
("Side(Kızılot)", "Alanya(Konaklı)"): 60,
("Side(Kızılot)", "Alanya"): 75,
("Side(Kızılot)", "Alanya(Mahmutlar)"): 80,
("Side(Kızılot)", "Antalya(AVM)"): 120,
("Side(Kızılot)", "Diğer"): 0,
("Side(Çenger)", "Antalya Havaliman"): 65,
("Side(Çenger)", "Kemer(Beldibi)"): 105,
("Side(Çenger)", "Kemer(Göynük)"): 105,
("Side(Çenger)", "Kemer(Kiriş)"): 115,
("Side(Çenger)", "Kemer"): 105,
("Side(Çenger)", "Kemer(Çamyuva)"): 115,
("Side(Çenger)", "Kemer(Tekirova)"): 115,
("Side(Çenger)", "Antalya(Kundu)"): 65,
("Side(Çenger)", "Antalya(Lara)"): 65,
("Side(Çenger)", "Antalya(Konyaaltı)"): 85,
("Side(Çenger)", "Belek(Kadriye)"): 55,
("Side(Çenger)", "Belek"): 55,
("Side(Çenger)", "Belek(Boğazkent)"): 55,
("Side(Çenger)", "Side(Gundoğdu)"): 35,
("Side(Çenger)", "Side(Çolaklı)"): 35,
("Side(Çenger)", "Side"): 35,
("Side(Çenger)", "Side(Sorgun)"): 30,
("Side(Çenger)", "Side(Kızılağaç)"): 30,
("Side(Çenger)", "Side(Kızılot)"): 30,
("Side(Çenger)", "Alanya(Okurcalar)"): 30,
("Side(Çenger)", "Alanya(Avsallar)"): 40,
("Side(Çenger)", "Alanya(Konaklı)"): 50,
("Side(Çenger)", "Alanya"): 65,
("Side(Çenger)", "Alanya(Mahmutlar)"): 70,
("Side(Çenger)", "Antalya(AVM)"): 130,
("Side(Çenger)", "Diğer"): 0,
("Alanya(Okurcalar)", "Antalya Havaliman"): 65,
("Alanya(Okurcalar)", "Kemer(Beldibi)"): 105,
("Alanya(Okurcalar)", "Kemer(Göynük)"): 105,
("Alanya(Okurcalar)", "Kemer(Kiriş)"): 115,
("Alanya(Okurcalar)", "Kemer"): 105,
("Alanya(Okurcalar)", "Kemer(Çamyuva)"): 115,
("Alanya(Okurcalar)", "Kemer(Tekirova)"): 115,
("Alanya(Okurcalar)", "Antalya(Kundu)"): 65,
("Alanya(Okurcalar)", "Antalya(Lara)"): 65,
("Alanya(Okurcalar)", "Antalya(Konyaaltı)"): 85,
("Alanya(Okurcalar)", "Belek(Kadriye)"): 55,
("Alanya(Okurcalar)", "Belek"): 55,
("Alanya(Okurcalar)", "Belek(Boğazkent)"): 55,
("Alanya(Okurcalar)", "Side(Gundoğdu)"): 45,
("Alanya(Okurcalar)", "Side(Çolaklı)"): 45,
("Alanya(Okurcalar)", "Side"): 45,
("Alanya(Okurcalar)", "Side(Sorgun)"): 45,
("Alanya(Okurcalar)", "Side(Kızılağaç)"): 45,
("Alanya(Okurcalar)", "Side(Kızılot)"): 45,
("Alanya(Okurcalar)", "Side(Çenger)"): 30,
("Alanya(Okurcalar)", "Alanya(Avsallar)"): 30,
("Alanya(Okurcalar)", "Alanya(Konaklı)"): 40,
("Alanya(Okurcalar)", "Alanya"): 55,
("Alanya(Okurcalar)", "Alanya(Mahmutlar)"): 60,
("Alanya(Okurcalar)", "Antalya(AVM)"): 130,
("Alanya(Okurcalar)", "Diğer"): 0,
("Alanya(Avsallar)", "Antalya Havaliman"): 70,
("Alanya(Avsallar)", "Kemer(Beldibi)"): 110,
("Alanya(Avsallar)", "Kemer(Göynük)"): 110,
("Alanya(Avsallar)", "Kemer(Kiriş)"): 120,
("Alanya(Avsallar)", "Kemer"): 110,
("Alanya(Avsallar)", "Kemer(Çamyuva)"): 120,
("Alanya(Avsallar)", "Kemer(Tekirova)"): 120,
("Alanya(Avsallar)", "Antalya(Kundu)"): 70,
("Alanya(Avsallar)", "Antalya(Lara)"): 70,
("Alanya(Avsallar)", "Antalya(Konyaaltı)"): 90,
("Alanya(Avsallar)", "Belek(Kadriye)"): 60,
("Alanya(Avsallar)", "Belek"): 60,
("Alanya(Avsallar)", "Belek(Boğazkent)"): 60,
("Alanya(Avsallar)", "Side(Gundoğdu)"): 50,
("Alanya(Avsallar)", "Side(Çolaklı)"): 50,
("Alanya(Avsallar)", "Side"): 50,
("Alanya(Avsallar)", "Side(Sorgun)"): 50,
("Alanya(Avsallar)", "Side(Kızılağaç)"): 50,
("Alanya(Avsallar)", "Side(Kızılot)"): 50,
("Alanya(Avsallar)", "Side(Çenger)"): 40,
("Alanya(Avsallar)", "Alanya(Okurcalar)"): 30,
("Alanya(Avsallar)", "Alanya(Konaklı)"): 30,
("Alanya(Avsallar)", "Alanya"): 45,
("Alanya(Avsallar)", "Alanya(Mahmutlar)"): 50,
("Alanya(Avsallar)", "Antalya(AVM)"): 140,
("Alanya(Avsallar)", "Diğer"): 0,
("Alanya(Konaklı)", "Antalya Havaliman"): 80,
("Alanya(Konaklı)", "Kemer(Beldibi)"): 120,
("Alanya(Konaklı)", "Kemer(Göynük)"): 120,
("Alanya(Konaklı)", "Kemer(Kiriş)"): 130,
("Alanya(Konaklı)", "Kemer"): 120,
("Alanya(Konaklı)", "Kemer(Çamyuva)"): 130,
("Alanya(Konaklı)", "Kemer(Tekirova)"): 130,
("Alanya(Konaklı)", "Antalya(Kundu)"): 80,
("Alanya(Konaklı)", "Antalya(Lara)"): 80,
("Alanya(Konaklı)", "Antalya(Konyaaltı)"): 100,
("Alanya(Konaklı)", "Belek(Kadriye)"): 70,
("Alanya(Konaklı)", "Belek"): 70,
("Alanya(Konaklı)", "Belek(Boğazkent)"): 70,
("Alanya(Konaklı)", "Side(Gundoğdu)"): 60,
("Alanya(Konaklı)", "Side(Çolaklı)"): 60,
("Alanya(Konaklı)", "Side"): 60,
("Alanya(Konaklı)", "Side(Sorgun)"): 60,
("Alanya(Konaklı)", "Side(Kızılağaç)"): 60,
("Alanya(Konaklı)", "Side(Kızılot)"): 60,
("Alanya(Konaklı)", "Side(Çenger)"): 50,
("Alanya(Konaklı)", "Alanya(Okurcalar)"): 40,
("Alanya(Konaklı)", "Alanya(Avsallar)"): 30,
("Alanya(Konaklı)", "Alanya"): 35,
("Alanya(Konaklı)", "Alanya(Mahmutlar)"): 40,
("Alanya(Konaklı)", "Antalya(AVM)"): 160,
("Alanya(Konaklı)", "Diğer"): 0,
("Alanya", "Antalya Havaliman"): 95,
("Alanya", "Kemer(Beldibi)"): 135,
("Alanya", "Kemer(Göynük)"): 135,
("Alanya", "Kemer(Kiriş)"): 145,
("Alanya", "Kemer"): 135,
("Alanya", "Kemer(Çamyuva)"): 145,
("Alanya", "Kemer(Tekirova)"): 145,
("Alanya", "Antalya(Kundu)"): 95,
("Alanya", "Antalya(Lara)"): 95,
("Alanya", "Antalya(Konyaaltı)"): 115,
("Alanya", "Belek(Kadriye)"): 85,
("Alanya", "Belek"): 85,
("Alanya", "Belek(Boğazkent)"): 85,
("Alanya", "Side(Gundoğdu)"): 75,
("Alanya", "Side(Çolaklı)"): 75,
("Alanya", "Side"): 75,
("Alanya", "Side(Sorgun)"): 75,
("Alanya", "Side(Kızılağaç)"): 75,
("Alanya", "Side(Kızılot)"): 75,
("Alanya", "Side(Çenger)"): 65,
("Alanya", "Alanya(Okurcalar)"): 55,
("Alanya", "Alanya(Avsallar)"): 45,
("Alanya", "Alanya(Konaklı)"): 35,
("Alanya", "Alanya(Mahmutlar)"): 35,
("Alanya", "Antalya(AVM)"): 190,
("Alanya", "Diğer"): 0,
("Alanya(Mahmutlar)", "Antalya Havaliman"): 100,
("Alanya(Mahmutlar)", "Kemer(Beldibi)"): 140,
("Alanya(Mahmutlar)", "Kemer(Göynük)"): 140,
("Alanya(Mahmutlar)", "Kemer(Kiriş)"): 150,
("Alanya(Mahmutlar)", "Kemer"): 140,
("Alanya(Mahmutlar)", "Kemer(Çamyuva)"): 150,
("Alanya(Mahmutlar)", "Kemer(Tekirova)"): 150,
("Alanya(Mahmutlar)", "Antalya(Kundu)"): 100,
("Alanya(Mahmutlar)", "Antalya(Lara)"): 100,
("Alanya(Mahmutlar)", "Antalya(Konyaaltı)"): 120,
("Alanya(Mahmutlar)", "Belek(Kadriye)"): 90,
("Alanya(Mahmutlar)", "Belek"): 90,
("Alanya(Mahmutlar)", "Belek(Boğazkent)"): 90,
("Alanya(Mahmutlar)", "Side(Gundoğdu)"): 80,
("Alanya(Mahmutlar)", "Side(Çolaklı)"): 80,
("Alanya(Mahmutlar)", "Side"): 80,
("Alanya(Mahmutlar)", "Side(Sorgun)"): 80,
("Alanya(Mahmutlar)", "Side(Kızılağaç)"): 80,
("Alanya(Mahmutlar)", "Side(Kızılot)"): 80,
("Alanya(Mahmutlar)", "Side(Çenger)"): 70,
("Alanya(Mahmutlar)", "Alanya(Okurcalar)"): 60,
("Alanya(Mahmutlar)", "Alanya(Avsallar)"): 50,
("Alanya(Mahmutlar)", "Alanya(Konaklı)"): 40,
("Alanya(Mahmutlar)", "Alanya"): 35,
("Alanya(Mahmutlar)", "Antalya(AVM)"): 200,
("Alanya(Mahmutlar)", "Diğer"): 0,
}

@app.get("/")
def root():
    return {"message": "Transfer API is running"}

class PriceByRegionRequest(BaseModel):
    from_address: str
    to_address: str

@app.post("/get-price")
def get_price(data: PriceByRegionRequest):
    key = (data.from_address, data.to_address)
    price = route_prices.get(key)
    if price is None:
        return {"error": "Маршрут не найден"}
    return {"price": price}

class BookingRequest(BaseModel):
    from_address: str
    to_address: str
    travel_date: str
    adults: int
    children: int
    comment: str = ""
    need_wifi: bool = False
    russian_driver: bool = False
    promo_code: str = ""

from fastapi.responses import JSONResponse

@app.post("/book-transfer", response_model=dict)
def book_transfer(data: BookingRequest):
    ...
    return {"status": "success", "message": "Бронирование принято", "price": data.price}

    message = (
        "📥 Новое бронирование:\n\n"
        f"🚗 Маршрут: {data.from_address} → {data.to_address}\n"
        f"📅 Дата: {data.travel_date}\n"
        f"👨‍👩‍👧 Взрослые: {data.adults}, Дети: {data.children}\n"
        f"💵 Цена: {price} $\n"
        f"📡 Wi-Fi: {'Да' if data.need_wifi else 'Нет'}\n"
        f"🇷🇺 Рус. водитель: {'Да' if data.russian_driver else 'Нет'}\n"
        f"📝 Комментарий: {data.comment or '—'}"
    )
    send_telegram_message(message)
    return {"status": "success", "message": "Бронирование принято", "price": price}

def send_telegram_message(text: str):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": text
    }
    try:
        httpx.post(url, json=payload, timeout=10)
    except Exception as e:
        print("Ошибка при отправке в Telegram:", e)
