services:
  - type: web
    name: transfer-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromDotEnv: true
      - key: TELEGRAM_CHAT_ID
        fromDotEnv: true
